### ISSUE TITLE
Welcome to SEBC

### ISSUE THREAD

**Issue by mfernest** [gang1998/SEBC#1]
It appears your repository files have not yet been published, and the labels and milestones are not yet configured.

Please ask me or @godiswc for assistance if you need it.

**Comment by gang1998** [comment]
I have created the milestones and update the labels, but I can't use git push to update my reposity. I also created a branch sebc-shanghai-2017. When run the command, I got the error blow:
$ git push –u origin sebc-shanghai-2017
error: src refspec origin does not match any.
error: src refspec sebc-shanghai-2017 does not match any.
error: failed to push some refs to '–u'
Is anything I missed? Thanks

**Comment by gang1998** [comment]
I resolved the issues by reinitialized the reposity.
